=== kvinther/RpgSimulator/scenario/AnExample/xml/scene.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="basictypes.xsd"/>
    
    <!-- DEFINE: exit -->
    <xs:complexType name="exit">
        <xs:sequence>
            <!-- If no desciption is given, we simply use "name" as the description. -->
            <xs:element name="description" type="description" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="ref" type="xs:string"/>
    </xs:complexType>
    
    <!-- DEFINE: location -->
    <xs:complexType name="location">
        <xs:sequence>
            <!-- If no desciption is given, we simply use "name" as the description. -->
            <xs:element name="description" type="description" minOccurs="0"/>
            <xs:element name="stuff" minOccurs="0">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="container" type="container" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                </xs:complexType>    
            </xs:element>
            <xs:element name="exits" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="exit" type="exit" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- DEFINE: scene-->
    <xs:element name="scene">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comments" minOccurs="0" type="xs:string"/>
                <xs:element name="locations" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="location" type="location" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kvinther/RpgSimulator/sandbox/Scenario/Scenario.Test/TestFiles/the-road.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="scene.xsd"
       id="the-road">
    <comments>
        In this scene the players will travel along an old road the leads to the mansion.
    </comments>
    <locations>
        <location id="mansion" name="The end of the road">
            <exits>
                <exit name="The road leads into a driveway before the mansion." ref="mansion/driveway" />
                <exit name="The road winds its way back towards the village." ref="road2"/>
            </exits>
        </location>
        <location id="road2" name="The old road">
            <exits>
                <exit name="The road continues." ref="mansion"/>
                <exit name="The road winds its way back towards the village." ref="road1"/>
            </exits>
        </location>
        <location id="road1" name="The old road">
            <exits>
                <exit name="The road towards the mansion." ref="road2"/>
                <exit name="Back to the village" ref="village/old-road">
                    <description>
                        The road winds its way back towards the village. 
                        <if cond="world/season=fall">Fallen leaves almost cover the road.</if>
                    </description>
                </exit>
            </exits>
        </location>
    </locations>
</scene>
